name: CI

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["master", "main"]

jobs:
  build-test:
    name: Lint, Typecheck, Build, Test (Coverage >= 90%)
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Enforce minimum coverage 90%
        run: node scripts/check-coverage.js 90

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage/**
          if-no-files-found: ignore
