import mongoose, { Document, Schema } from 'mongoose';

export interface IPhoneNumber extends Document {
    userId: string;
    phoneNumber: string;
    provider: 'exotel' | 'twilio' | 'other';
    displayName: string;
    
    // Exotel Configuration
    exotelConfig?: {
        apiKey: string;
        apiToken: string;
        sid: string; // Exotel SID
        appId?: string;
        domain: string; // e.g., 'api.exotel.com' or 'api.in.exotel.com'
        region: string; // e.g., 'in' for India, 'us' for USA
    };
    
    // Agent linking
    linkedAgentId?: string;
    
    // Webhook URLs (generated by system)
    webhookUrl?: string;
    websocketUrl?: string;
    
    // Status
    status: 'active' | 'inactive' | 'error';
    lastUsed?: Date;
    
    // Metadata
    createdAt: Date;
    updatedAt: Date;
}

const PhoneNumberSchema: Schema = new Schema(
    {
        userId: {
            type: String,
            required: true,
            index: true,
        },
        phoneNumber: {
            type: String,
            required: true,
            unique: true,
            trim: true,
        },
        provider: {
            type: String,
            enum: ['exotel', 'twilio', 'other'],
            default: 'exotel',
        },
        displayName: {
            type: String,
            required: true,
            trim: true,
        },
        exotelConfig: {
            apiKey: {
                type: String,
                required: function(this: IPhoneNumber) {
                    return this.provider === 'exotel';
                },
            },
            apiToken: {
                type: String,
                required: function(this: IPhoneNumber) {
                    return this.provider === 'exotel';
                },
            },
            sid: {
                type: String,
                required: function(this: IPhoneNumber) {
                    return this.provider === 'exotel';
                },
            },
            appId: String,
            domain: {
                type: String,
                default: 'api.in.exotel.com',
            },
            region: {
                type: String,
                default: 'in',
            },
        },
        linkedAgentId: {
            type: String,
        },
        webhookUrl: String,
        websocketUrl: String,
        status: {
            type: String,
            enum: ['active', 'inactive', 'error'],
            default: 'active',
        },
        lastUsed: Date,
    },
    {
        timestamps: true,
    }
);

// Create composite indexes for efficient queries
PhoneNumberSchema.index({ userId: 1, status: 1 });
PhoneNumberSchema.index({ linkedAgentId: 1 });
PhoneNumberSchema.index({ phoneNumber: 1 }, { unique: true, background: true });

export default mongoose.models.PhoneNumber || mongoose.model<IPhoneNumber>('PhoneNumber', PhoneNumberSchema);
